#!/bin/bash
# Convert index.html and xterm.js into a C++ header file.

set -e

OUTPUT_FILE="src/common/embedded_assets.hpp"

echo "// Generated by embed-assets.sh. Do not edit." > "$OUTPUT_FILE"
echo "#pragma once" >> "$OUTPUT_FILE"
echo "#include <vector>" >> "$OUTPUT_FILE"

# Helper function to generate hex array via python
embed_file() {
    local filepath=$1
    local varname=$2
    echo "Embedding $filepath as $varname"
    
    echo "const std::vector<unsigned char> $varname = {" >> "$OUTPUT_FILE"
    python3 -c "
import sys
with open('$filepath', 'rb') as f:
    data = f.read()
    hex_data = [f'0x{b:02x}' for b in data]
    print(', '.join(hex_data))
" >> "$OUTPUT_FILE"
    echo "};" >> "$OUTPUT_FILE"
}

embed_file "web/index.html" "INDEX_HTML"
embed_file "web/xterm.js" "XTERM_JS"
embed_file "web/xterm.css" "XTERM_CSS"
embed_file "web/xterm-addon-fit.js" "XTERM_ADDON_FIT_JS"
