#!/bin/bash
################################
# Embed web assets as C++ byte arrays (xxd pipeline).
################################

set -e

OUTPUT_FILE="src/common/embedded_assets.hpp"

{
    echo "// Generated by embed-assets.sh. Do not edit."
    echo "#pragma once"
    echo "#include <vector>"
} > "$OUTPUT_FILE"

embed_file() {
    local filepath=$1
    local varname=$2
    echo "Embedding $filepath as $varname"

    {
        echo "const std::vector<unsigned char> $varname = {"
        xxd -i < "$filepath"
        echo "};"
    } >> "$OUTPUT_FILE"
}

embed_file "web/index.html" "INDEX_HTML"
embed_file "web/xterm.js" "XTERM_JS"
embed_file "web/xterm.css" "XTERM_CSS"
embed_file "web/xterm-addon-fit.js" "XTERM_ADDON_FIT_JS"
